name: Front End Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STATIC_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STATIC_DEPLOY }}
          aws-region: us-west-1
      - name: Install dependencies
        run: npm install
      - name: Get Hugo Modules
        run: hugo mod get ./...
      - name: Build
        run: hugo --minify
      - name: Store in S3 bucket
        run: aws s3 sync ./public/ s3://portfolio-website-static-bucket/ --delete
      - name: Invalidate cloudfront Dist Cache
        run: aws cloudfront create-invalidation --distribution-id E32JWBEBSAC70X --paths "/*"
